### ISSUE TITLE
Getting RuntimeError: CUDA error: invalid argument

### ISSUE THREAD

**Issue by prams628** [locuslab/SATNet#13]
Hi,
I was trying to run the SATNet model on a custom project and I'm seeing the following error:

```
Traceback (most recent call last):
  File "kakuro_solver_satnet.py", line 175, in <module>
    train(
  File "kakuro_solver_satnet.py", line 113, in train
    run(epoch, model, optimizer, dataset, batchSz, device, to_train=True)
  File "kakuro_solver_satnet.py", line 95, in run
    preds = model(b_data.contiguous(), b_is_input.contiguous())
  File "/home/pramod/MS/SEM-1/NSR/NeuroSymbolicReasoning/nsr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "kakuro_solver_satnet.py", line 32, in forward
    out = self.sat(batch, mask)
  File "/home/pramod/MS/SEM-1/NSR/NeuroSymbolicReasoning/nsr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pramod/MS/SEM-1/NSR/SATNet/satnet/models.py", line 154, in forward
    z = MixingFunc.apply(self.S, z, is_input, self.max_iter, self.eps, self.prox_lam)
  File "/home/pramod/MS/SEM-1/NSR/SATNet/satnet/models.py", line 51, in forward
    satnet_impl.forward(max_iter, eps,
RuntimeError: CUDA error: invalid argument
```

However, when I try to run the same piece of code using CPU, it works perfectly fine.

My coding environment:
```
>>> torch.__version__: '1.7.1+cu101'
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

I'm using a GeForce GTX 1650 GPU.

The code I'm using is:
```
class KakuroSolver(nn.Module):

    def __init__(self, n, m, aux):
        super(KakuroSolver, self).__init__()
        self.sat = satnet.SATNet(n, m, aux)

    def forward(self, batch, mask):
        out = self.sat(batch, mask)
        return out


def get_device(use_gpu=True):
    if torch.cuda.is_available() and use_gpu:
        print(f'GPU available: {torch.cuda.get_device_name()}')
        device = torch.device('cuda')
    else:
        print('No GPU available or forbidden from usage. Using CPU')
        device = torch.device('cpu')
    return device

def run(epoch, model, optimizer, dataset, batchSz, device, to_train):

    loss_final = 0

    loader = torch.utils.data.DataLoader(dataset, batch_size=batchSz, drop_last=True)

    for idx, (data, is_input, label) in enumerate(loader):
        # transfer the data to the designated device.
        b_data = data.to(device)
        b_is_input = is_input.to(device)
        b_label = label.to(device)

        if to_train: optimizer.zero_grad()
        print(b_data.shape, b_is_input.shape)
        preds = model(b_data.contiguous(), b_is_input.contiguous())
        if idx == len(loader) - 1 and epoch == NO_OF_EPOCHS:
            print(preds)
        loss = nn.functional.binary_cross_entropy(preds, b_label)

        if to_train:
            loss.backward()
            optimizer.step()

        loss_final += loss.item()

    loss_final = loss_final/len(loader)
    print('RESULTS: Average loss: {:.4f}'.format(loss_final))

    torch.cuda.empty_cache()


def train(epoch, model, optimizer, dataset, batchSz, device):
    run(epoch, model, optimizer, dataset, batchSz, device, to_train=True)


@torch.no_grad()
def test(epoch, model, optimizer, dataset, batchSz, device):
    run(epoch, model, optimizer, dataset, batchSz, device, to_train=False)


# The code here simulates the generation of vectors I'll finally have
X = torch.randint(2, (195, 2288)).type(torch.int32)
is_input = torch.randint(2, (195, 2288)).type(torch.int32)
y = torch.randint(2, (195, 2288)).type(torch.float64)

X_train, X_test, y_train, y_test, is_input_train, is_input_test =\
    train_test_split(X, y, is_input, test_size=0.2)
train_dataset = torch.utils.data.TensorDataset(X_train, is_input_train, y_train)

solver = KakuroSolver(2288, X.shape[1], 30)

# get ready to train
# fetch the device which will be used to train
use_gpu = False if len(sys.argv) > 1 and sys.argv[1] == '0' else True
device = get_device(use_gpu)

# move the model to the `device`
solver.to(device)

print('Starting the training process...')
optimizer = torch.optim.Adam(solver.parameters(), lr=LEARNING_RATE)
for epoch in range(1, NO_OF_EPOCHS + 1):
    train(
        epoch=epoch,
        model=solver,
        optimizer=optimizer,
        dataset=train_dataset,
        batchSz=BATCH_SIZE,
        device=device
    )
```

Could you please help me find a solution to this issue?

**Comment by prams628** [comment]
Also, I thought it might be a local issue due to which I tried to run the same code on google colab with GPU. The same error was observed there as well.
TIA!

**Comment by prams628** [comment]
Hi,
I was able to circumvent this issue by simply changing the type of the `X` tensor. Not sure why it fixed the issue though.
By the way, thank you very much for making this project public.

**Comment by xflash96** [comment]
Thanks for letting us know!
